import Head from "next/head";
import { motion } from "framer-motion";

import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LargeCard from "../components/LargeCard";
import MediumCard from "../components/MediumCard";
import SmallCard from "../components/SmallCard";
import smallCardImage from "/public/images/3643ec104098983.5f5b5ea7c10c5.png";

const smallCardData = [
  {
    _id: "631b14cc00036d4bfd1fcdeb",
    img: "https://i.postimg.cc/LsbVVg8s/london-tower-bridge-across-the-river-thames-famous-landmark-building-in-united-kingdom-illustration.webp",
    distance: "$189/night avg",
    location: "London",
    time: "2022-09-10T05:57:10.928Z",
    __v: 0,
  },
  {
    _id: "631b14cc00036d4bfd1fcded",
    img: "https://i.postimg.cc/6pZL2rP9/summer-swimming-pool-jpeg-pagespeed-ce-H1808fl-Ljp.jpg",
    distance: "$98/night avg",
    location: "Copenhagen",
    time: "2022-09-10T05:57:10.923Z",
    __v: 0,
  },
  {
    _id: "631b14cc00036d4bfd1fcdec",
    img: "https://i.postimg.cc/8kHfJJ52/istockphoto-626586892-612x612.jpg",
    distance: "$209/night avg",
    location: "Manchester",
    time: "2022-09-10T05:57:10.930Z",
    __v: 0,
  },
  {
    _id: "631b14cc00036d4bfd1fcdf2",
    img: "https://i.postimg.cc/ZRwrtVWL/summer-art-illustration-jpg-pagespeed-ce-knat-Q9zw-UX.jpg",
    distance: "$78/night avg",
    location: "Charleston",
    time: "2022-09-10T05:57:10.935Z",
    __v: 0,
  },
  {
    _id: "631b14cc00036d4bfd1fcdef",
    img: "https://i.postimg.cc/1zpHTG0W/summer-island.jpg",
    distance: "$108/night avg",
    location: "Florence",
    time: "2022-09-10T05:57:10.937Z",
    __v: 0,
  },
  {
    _id: "631b14cc00036d4bfd1fcdee",
    img: "https://i.postimg.cc/B6nKgHmP/perfect-isolation-illustration-tubikarts-jpg-pagespeed-ce-y-Fs3f-Xk-Kb.jpg",
    distance: "$78/night avg",
    location: "Montreal",
    time: "2022-09-10T05:57:10.938Z",
    __v: 0,
  },
  {
    _id: "631b14cc00036d4bfd1fcdf1",
    img: "https://i.postimg.cc/XYYjBcLT/tumblr-oahhh5muxc1qlioplo1-1280.jpg",
    distance: "$178/night avg",
    location: "Saint Petersburg",
    time: "2022-09-10T05:57:10.931Z",
    __v: 0,
  },
  {
    _id: "631b14cc00036d4bfd1fcdf0",
    img: "https://i.postimg.cc/R0z1c3rw/summer-landscape-sea-jpeg-pagespeed-ce-h-TFufen-Rj-C.jpg",
    distance: "$123/night avg",
    location: "Geneva",
    time: "2022-09-10T05:57:10.933Z",
    __v: 0,
  },
];

const mediumCarData = [
  {
    _id: "631c2824747442c0d65039df",
    img: "https://i.postimg.cc/HLSYdSyS/Cheung-Twentynine-Palms-18332523-0446-HLP-169crop.webp",
    title: "Simplifying the check-in process",
    time: "2022-09-10T06:01:08.917Z",
    __v: 0,
  },
  {
    _id: "631c2824747442c0d65039e1",
    img: "https://i.postimg.cc/vmMmhgrs/image16.webp",
    title: "Making your home ready for guests",
    time: "2022-09-10T06:01:08.926Z",
    __v: 0,
  },
  {
    _id: "631c2824747442c0d65039e0",
    img: "https://i.postimg.cc/L60MbqjP/2-UV408-PU6-DPYG.webp",
    title: "Thoughtful details guests love",
    time: "2022-09-10T06:01:08.924Z",
    __v: 0,
  },
  {
    _id: "631c2824747442c0d65039e4",
    img: "https://i.postimg.cc/qvzQ1qGz/2-UV408-WEJB1-AV.webp",
    title: "Simplify your communication",
    time: "2022-09-10T06:01:08.932Z",
    __v: 0,
  },
  {
    _id: "631c2824747442c0d65039e3",
    img: "https://i.postimg.cc/htW6Q9nK/2-UV408-TAS5-L93.webp",
    title: "Keeping your space clean",
    time: "2022-09-10T06:01:08.928Z",
    __v: 0,
  },
  {
    _id: "631c2824747442c0d65039e2",
    img: "https://i.postimg.cc/rsBzcdxf/trump-hotel-chicago-illinois-usa.webp",
    title: "The pros of spending a night in your space",
    time: "2022-09-10T06:01:08.927Z",
    __v: 0,
  },
];

type HomeProps = {};

const Home = ({}: HomeProps) => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
      className="overflow-x-hidden"
    >
      <Head>
        <title>Airbnb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://brandlogos.net/wp-content/uploads/2022/07/airbnb-logo_brandlogos.net_vb6uh-512x512.png"
        />
      </Head>
      <Header />
      <Banner />

      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-3xl font-semibold pb-5">Explore Nearby</h2>
          {/* data from sever */}
          <div
            className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3
          xl:grid-cols-4"
          >
            {smallCardData?.map((item: any) => (
              <SmallCard
                key={item.img}
                img={item.img}
                distance={item.distance}
                location={item.location}
              />
            ))}
          </div>
        </section>
        <section>
          <h2 className="text-3xl font-semibold py-8">Live Anywhere</h2>
          <div
            className="flex space-x-3 overflow-scroll scrollbar-hide p-3
          -ml-3"
          >
            {mediumCarData?.map((item: any) => (
              <MediumCard key={item.img} img={item.img} title={item.title} />
            ))}
          </div>
        </section>
        <LargeCard
          img={smallCardImage}
          title="The Greatest Outdoors"
          description="wishlists curated by Airbnb"
          buttonText="Get Inspired"
        />
      </main>
      <Footer />
    </motion.div>
  );
};

export default Home;
