import Head from "next/head";
import { motion } from "framer-motion";

import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LargeCard from "../components/LargeCard";
import MediumCard from "../components/MediumCard";
import SmallCard from "../components/SmallCard";
import smallCardImage from "/public/images/3643ec104098983.5f5b5ea7c10c5.png";
import mediumCarData from "../utils/mediumCarData";
import smallCardData from "../utils/smallCardData";

type HomeProps = {};

const Home = ({}: HomeProps) => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
      className="overflow-x-hidden"
    >
      <Head>
        <title>Airbnb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://brandlogos.net/wp-content/uploads/2022/07/airbnb-logo_brandlogos.net_vb6uh-512x512.png"
        />
      </Head>
      <Header />
      <Banner />

      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-3xl font-semibold pb-5">Explore Nearby</h2>
          {/* data from sever */}
          <div
            className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3
          xl:grid-cols-4"
          >
            {smallCardData?.map((item: any) => (
              <SmallCard
                key={item.img}
                img={item.img}
                distance={item.distance}
                location={item.location}
              />
            ))}
          </div>
        </section>
        <section>
          <h2 className="text-3xl font-semibold py-8">Live Anywhere</h2>
          <div
            className="flex space-x-3 overflow-scroll scrollbar-hide p-3
          -ml-3"
          >
            {mediumCarData?.map((item: any) => (
              <MediumCard key={item.img} img={item.img} title={item.title} />
            ))}
          </div>
        </section>
        <LargeCard
          img={smallCardImage}
          title="The Greatest Outdoors"
          description="wishlists curated by Airbnb"
          buttonText="Get Inspired"
        />
      </main>
      <Footer />
    </motion.div>
  );
};

export default Home;
